apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
data:
  host: mysql-service
  dbname: testdb

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service
          image: mahhans02/backend_spring_scanned:v7
          env:
            - name: MYSQL_PASSWORD
              # value: '123456'
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DBNAME
              # value: 'testdb'
              valueFrom:
                configMapKeyRef:
                  name: mysql-conf
                  key: dbname
            - name: MYSQL_HOST
              # value: 'mysql-service'
              valueFrom:
                configMapKeyRef:
                  name: mysql-conf
                  key: host
          ports:
            - name: backend-port
              containerPort: 8081
          

