apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
spec:
  limits:
  - type: Container
    max:
      memory: 1Gi
    min:
      memory: 100Mi
    default:
      memory: 256Mi
    max:
      cpu: "1"
    min:
      cpu: 100m
    default:
      cpu: 200m
